name: Deploy Flask API via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH to VM
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          cd data-ops-3 || git clone git@github.com:${{ github.repository }}.git data-ops-3 && cd data-ops-3
          git pull origin main
          docker build -t flask-api .
          docker stop flask-api || true
          docker rm flask-api || true
          docker run -d -p 80:80 --name flask-api flask-api
