version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: ./app
    depends_on:
      - db
    ports:
      - "5000:5000"

volumes:
  db_data:
