name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Conectar com a VM e fazer o deploy
      uses: appleboy/ssh-action@v0.1.8

      with: 
        host: ${{ secrets.VM_HOST}}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/${{ secrets.VM_USER }}/data-ops-3
          git pull origin main
          sudo docker-compose down || true
          sudo docker-compose up -d --build