name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Connect to VM and deploy
      run: |
        ssh -o StrictHostKeyChecking=no azureuser@20.169.107.205 << 'EOF'
          cd /path/to/your/app
          git pull origin main
          docker build -t flask-app .
          docker stop flask-app || true
          docker rm flask-app || true
          docker run -d -p 80:80 --name flask-app flask-app
        EOF